### ISSUE TITLE
How to link to further documentation

### ISSUE THREAD

**Issue by fofr** [alphagov/styleguides#67]
(Opening this issue for discussion)

In the guidance about use of READMEs it says:

> use the docs directory liberally, and link out to it from the README

If the `/docs` are long and quite involved, where is best to put a contents list? For https://github.com/alphagov/govuk_frontend_toolkit/pull/161 I've used "Documentation" as the header and listed the contents of the docs below it. I've put this at the end of the README, just before the licence.

![screen shot 2015-03-09 at 14 00 49](https://cloud.githubusercontent.com/assets/319055/6556359/cbb54db6-c664-11e4-8732-c13b688a43f0.png)

This feels like something we should do consistently.

**Comment by benlovell** [comment]
In the [canonical ruby style guide](https://github.com/bbatsov/ruby-style-guide) they employ super-script anchors that can be referenced to land folks directly at specific guidance. I was toying with adding these to the ruby guidance here, to open discussion.

**Comment by rubenarakelyan** [comment]
This guidance has moved to https://docs.publishing.service.gov.uk/manual/readmes.html so probably better to open an issue on that.
