### ISSUE TITLE
Sharing specific document sub-sections.

### ISSUE THREAD

**Issue by harryharrold** [alphagov/styleguides#68]
Documents such as the introductory guide to open internet tools for civil servants available at https://www.gov.uk/government/publications/digital-skills-in-the-civil-service/an-introductory-guide-to-open-internet-tools-for-civil-servants are extremely useful for sharing specific information with civil service (and other) colleagues.

However, it is not trivial to link to a specific sub-section within that document; such as, for example, "I need to gather opinions or information from a group of people". While it can be done by appending the CSS ID for the section to the address to give: https://www.gov.uk/government/publications/digital-skills-in-the-civil-service/an-introductory-guide-to-open-internet-tools-for-civil-servants#i-need-to-gather-opinions-or-information-from-a-group-of-people that's not trivial. 

I would like to see some other method of making such sections addresses easy to identify and share: perhaps simply adding an anchor to each H3 would be sufficient, perhaps something visual might work, perhaps I am simply a very unusual user and no change is needed.

**Comment by RosalynV** [comment]
Thanks for raising this issue. I've logged it in the relevant [improvement plan](https://insidegovuk.blog.gov.uk/2015/03/13/introducing-improvement-plans/) for publications, we'll consider it when we look at improving the publications format as a whole.

The best way to raise issues like this in the future is through the "Is there anything wrong with this page?" link at the bottom of the page (or through signon>support if you work in a government department and have an account). That raises a ticket with our support desk who can then record it, link it to any similar reports and make sure they get to the relevant team.
