### ISSUE TITLE
Update JavaScript styleguide to use Standard

### ISSUE THREAD

**Issue by tvararu** [alphagov/styleguides#97]
We've been trying out [standardjs](http://standardjs.com/) on a few of our codebases:

- https://github.com/alphagov/govuk_prototype_kit/pull/224
- https://github.com/alphagov/govuk_elements/pull/290
- https://github.com/alphagov/govuk_frontend_toolkit/pull/334

It seems like it's been well received. I think we should make it part of our JavaScript styleguide. I see this as three parts:

- removing what is already defined in the [Standard guidelines](http://standardjs.com/rules.html)
- adding our reasoning behind using Standard, which can be pulled from the [prototype kit](https://github.com/alphagov/govuk_prototype_kit/blob/ec0851ae3fb7f31809d579bc102fc4e682944b79/docs/linting.md)
- updating any examples to adhere to the new style

**Comment by ChrisBAshton** [comment]
Looks like this was done in January 2017: https://github.com/alphagov/styleguides/commits/master/js.md
